### ISSUE TITLE
paper_weigths in python file interface.py (line 183) should be a string. 

### ISSUE THREAD

**Issue by utkd135** [compphoto/IntrinsicCompositing#2]
Attached picture has the highlighted error:
<img width="360" alt="IC_paper_Weights" src="https://github.com/compphoto/IntrinsicCompositing/assets/79432685/89dd1200-f872-4d38-a8fb-6b840c56dca4">

**Comment by CCareaga** [comment]
You're right, not sure how that wasn't caught, thanks for pointing it out! I've fixed it in the latest commit.
