### ISSUE TITLE
Couldn't run interface.py correctly

### ISSUE THREAD

**Issue by EthanJ666** [compphoto/IntrinsicCompositing#5]
shutil.Error: Destination path 'C:\Users\lenovo/.cache\torch\hub/omnidata/w9bbyn6ytmp' already exists.
How should I fix this bug?

**Comment by CCareaga** [comment]
I haven't seen this, but it appears to be coming from the automatic downloading of the omnidata normal estimation weights. It looks like that's a temporary file created while PyTorch is downloading the weights, so maybe the download was stopped at some point and it wasn't cleaned up? Maybe you could try deleting that file and re-running.

**Comment by EthanJ666** [comment]
Still popping out this error. I'm going to try it in my other pc to see whether the same error would occur.
Edit: Okay it still appers, weird

**Comment by CCareaga** [comment]
This is the code that downloads the weights when you first run the normal estimation model:

https://github.com/CCareaga/omnidata/blob/main/omnidata_tools/model_util.py

Just to get it working you can download the weights manually from here:

https://drive.google.com/uc?id=1wNxVO4vVbDEMEpnAi_jwQObf2MFodcBR

and place them in the directory you get from: `torch.hub.get_dir() + '/omnidata/'` which for you appears to be `C:\Users\lenovo/.cache\torch\hub/omnidata/`. From that directory it looks like you're using Windows. I developed and tested the interface on Ubuntu, so it may not run correctly on Windows (this could also be the source of this error). 

Hopefully that helps, I can try getting it running on Windows to see what issues there are if you aren't able to get things running.

**Comment by EthanJ666** [comment]
Thanks so much, will try it first!
