### ISSUE TITLE
specular highlights

### ISSUE THREAD

**Issue by junzhoupro** [compphoto/IntrinsicCompositing#7]
Hi thanks for your cool work.
As the intrinsic decompostion now is updated with specular components, do you have plan to update this work to support specular lights?

**Comment by CCareaga** [comment]
The method in it's current state can handle some amount of specular intensity, but it's unlikely that the reshading network will predict specularity properly. It's true that our new method could help improve this by explicitly modeling specularity prediction. Furthermore modeling the colorful illumination in the scene could also greatly improve this method, but we don't plan on extending this method. I think this is a promising direction for future research in this area though.
